"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type WorkspaceRow={id:string;name:string;owner_email:string;created_at:string;trial_ends_at:string;workspace_plan:string;license_status:string|null;plan_code:string|null;provider:string|null;current_period_ends_at:string|null;member_count:number;map_count:number;node_count:number;effective_status:string};
type PlanRow={code:string;name:string;description:string;price_cents:number;currency:string;billing_interval:"month"|"year";provider_price_id:string;trial_days:number;active:number;highlighted:number;updated_at:string};
type EventRow={id:string;workspace_id:string|null;provider:string;event_type:string;status:string;amount_cents:number;currency:string;created_at:string};
type AdminData={currentAdmin:{name:string;email:string};metrics:{workspaces:number;trials:number;subscribers:number;attention:number;canceled:number;estimatedMrrCents:number;maps:number;nodes:number};workspaces:WorkspaceRow[];plans:PlanRow[];events:EventRow[];configuration:{checkoutConfigured:boolean;authentication:string;integration:{provider:string;environment:"sandbox"|"production";apiKeyConfigured:boolean;webhookTokenConfigured:boolean;webhookUrl:string}}};

const money=(cents:number)=>(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date=(value:string|null)=>value?new Date(value).toLocaleDateString("pt-BR"):"Sem vencimento";
const futureDate=(days:number)=>new Date(new Date().getTime()+days*86_400_000).toISOString();
const statusText:Record<string,string>={trialing:"Teste",active:"Ativa",past_due:"Pendente",canceled:"Cancelada",suspended:"Suspensa",expired:"Expirada",incomplete:"Incompleta"};

async function apiBody(response:Response){
  const text=await response.text();
  if(!text)throw new Error(`O servidor respondeu sem dados (${response.status}). Tente novamente em instantes.`);
  try{return JSON.parse(text) as Record<string,unknown>}catch{throw new Error(`O servidor devolveu uma resposta inválida (${response.status}).`)}
}

export default function AdminDashboard({initialAdmin}:{initialAdmin:{name:string;email:string}}){
  const [data,setData]=useState<AdminData|null>(null),[tab,setTab]=useState<"overview"|"customers"|"licenses"|"settings">("overview"),[settingsTab,setSettingsTab]=useState<"plans"|"integrations"|"security">("plans"),[search,setSearch]=useState(""),[busy,setBusy]=useState(""),[toast,setToast]=useState(""),[error,setError]=useState("");
  const load=()=>{setError("");return fetch("/api/admin",{cache:"no-store"}).then(async response=>{const body=await apiBody(response);if(!response.ok)throw new Error(String(body.error||"Não foi possível carregar o painel"));setData(body as unknown as AdminData)}).catch(reason=>setError(reason instanceof Error?reason.message:"Não foi possível carregar o painel"))};
  useEffect(()=>{load()},[]);
  const action=async(payload:Record<string,unknown>,label:string)=>{setBusy(label);setError("");try{const response=await fetch("/api/admin",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await apiBody(response);if(!response.ok)throw new Error(String(body.error||"Não foi possível concluir a ação"));setToast(String(body.message||"Alteração concluída"));await load()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível concluir a ação")}finally{setBusy("")}};
  const filtered=useMemo(()=>data?.workspaces.filter(item=>(item.name+item.owner_email+item.effective_status).toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" href="/"><span>MO</span><div><b>Mapa Operacional</b><small>SUPER ADMIN</small></div></Link><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><i>⌂</i>Visão geral</button><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}><i>♙</i>Clientes</button><button className={tab==="licenses"?"active":""} onClick={()=>setTab("licenses")}><i>◇</i>Licenças</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><i>⚙</i>Configurações</button></nav><footer><a href="/api/auth/logout">Sair da administração</a></footer></aside>
    <section className="admin-main"><header className="admin-topbar"><div><span>Painel do proprietário</span><b>{tab==="overview"?"Visão geral":tab==="customers"?"Clientes":tab==="licenses"?"Licenças":"Configurações"}</b></div><aside><span>{initialAdmin.name.slice(0,1).toUpperCase()}</span><div><b>{initialAdmin.name}</b><small>{initialAdmin.email}</small></div></aside></header>
      {toast&&<button className="admin-toast" onClick={()=>setToast("")}>✓ {toast}</button>}{error&&<button className="admin-toast error" onClick={()=>setError("")}>! {error}</button>}
      {!data?<div className="admin-loading">{error?<><b>O painel não conseguiu carregar.</b><button onClick={load}>Tentar novamente</button></>:"Preparando o painel administrativo..."}</div>:<div className="admin-content">
        {tab==="overview"&&<Overview data={data} onCustomers={()=>setTab("customers")} onSettings={()=>setTab("settings")}/>} 
        {tab==="customers"&&<Customers rows={filtered} search={search} setSearch={setSearch} busy={busy} onAction={action}/>} 
        {tab==="licenses"&&<Licenses rows={filtered} search={search} setSearch={setSearch} busy={busy} onAction={action}/>} 
        {tab==="settings"&&<Settings data={data} active={settingsTab} setActive={setSettingsTab} busy={busy} onAction={action}/>} 
      </div>}
    </section>
  </main>;
}

function Overview({data,onCustomers,onSettings}:{data:AdminData;onCustomers:()=>void;onSettings:()=>void}){
  const cards=[["Workspaces",data.metrics.workspaces,"Empresas cadastradas"],["Trials ativos",data.metrics.trials,"Em período de teste"],["Assinantes",data.metrics.subscribers,"Licenças ativas"],["MRR estimado",money(data.metrics.estimatedMrrCents),"Receita recorrente mensal"],["Atenção",data.metrics.attention,"Pendentes ou suspensas"],["Operação",`${data.metrics.maps} mapas`,`${data.metrics.nodes} etapas registradas`]];
  return <><section className="admin-heading"><div><span>SAÚDE DA PLATAFORMA</span><h1>O negócio inteiro,<br/>em uma única visão.</h1><p>Acompanhe clientes, licenças e atividade operacional sem entrar nos Workspaces.</p></div><button onClick={onCustomers}>Gerenciar clientes →</button></section><section className="metric-grid">{cards.map(([label,value,description])=><article key={label}><span>{label}</span><b>{value}</b><small>{description}</small></article>)}</section><div className="admin-two-columns"><section className="admin-card"><header><div><span>CLIENTES RECENTES</span><h2>Novos Workspaces</h2></div><button onClick={onCustomers}>Ver todos</button></header><div className="compact-list">{data.workspaces.slice(0,6).map(row=><article key={row.id}><span>{row.name.slice(0,2).toUpperCase()}</span><div><b>{row.name}</b><small>{row.owner_email}</small></div><i className={row.effective_status}>{statusText[row.effective_status]||row.effective_status}</i></article>)}</div></section><section className="admin-card"><header><div><span>CONFIGURAÇÃO</span><h2>Pronto para vender?</h2></div><button onClick={onSettings}>Configurar</button></header><div className="readiness-list"><p><i className="ok">✓</i><span><b>Login seguro</b>Entrar com ChatGPT ativo</span></p><p><i className="ok">✓</i><span><b>Licenças</b>Controle automático e manual</span></p><p><i className={data.configuration.checkoutConfigured?"ok":"wait"}>{data.configuration.checkoutConfigured?"✓":"!"}</i><span><b>Asaas</b>{data.configuration.checkoutConfigured?"Checkout e webhook conectados":"Credenciais seguras pendentes"}</span></p></div></section></div></>;
}

function Customers({rows,search,setSearch,busy,onAction}:{rows:WorkspaceRow[];search:string;setSearch:(value:string)=>void;busy:string;onAction:(payload:Record<string,unknown>,label:string)=>void}){
  return <><ListHeader eyebrow="GESTÃO DE CLIENTES" title="Usuários e Workspaces" text="Acompanhe a operação de cada conta sem expor os dados internos dos mapas." search={search} setSearch={setSearch}/><section className="admin-table customers-table"><header><span>Cliente</span><span>Uso</span><span>Cadastro</span><span>Status</span><span>Ação</span></header>{rows.map(row=><article key={row.id}><div className="customer-cell"><i>{row.name.slice(0,2).toUpperCase()}</i><span><b>{row.name}</b><small>{row.owner_email}</small></span></div><span>{row.map_count} mapas · {row.member_count+1} pessoas</span><span>{date(row.created_at)}</span><i className={"status "+row.effective_status}>{statusText[row.effective_status]||row.effective_status}</i><button disabled={Boolean(busy)} onClick={()=>onAction({action:"extend_trial",workspaceId:row.id,days:7},"trial-"+row.id)}>+ 7 dias</button></article>)}</section></>;
}

function Licenses({rows,search,setSearch,busy,onAction}:{rows:WorkspaceRow[];search:string;setSearch:(value:string)=>void;busy:string;onAction:(payload:Record<string,unknown>,label:string)=>void}){
  return <><ListHeader eyebrow="CONTROLE COMERCIAL" title="Licenças da plataforma" text="Ative, suspenda ou renove acessos preservando todos os dados do cliente." search={search} setSearch={setSearch}/><section className="license-admin-grid">{rows.map(row=><article key={row.id}><header><div><span>{row.name.slice(0,2).toUpperCase()}</span><div><b>{row.name}</b><small>{row.owner_email}</small></div></div><i className={row.effective_status}>{statusText[row.effective_status]||row.effective_status}</i></header><dl><div><dt>Plano</dt><dd>{row.plan_code||row.workspace_plan}</dd></div><div><dt>Provedor</dt><dd>{row.provider||"Manual"}</dd></div><div><dt>Validade</dt><dd>{date(row.current_period_ends_at||row.trial_ends_at)}</dd></div></dl><footer><button disabled={Boolean(busy)} onClick={()=>onAction({action:"set_license",workspaceId:row.id,planCode:"monthly",status:"active",validUntil:futureDate(31)},"monthly-"+row.id)}>Ativar mensal</button><button disabled={Boolean(busy)} onClick={()=>onAction({action:"set_license",workspaceId:row.id,planCode:"annual",status:"active",validUntil:futureDate(365)},"annual-"+row.id)}>Ativar anual</button>{row.effective_status==="suspended"?<button className="success" onClick={()=>onAction({action:"set_license",workspaceId:row.id,planCode:row.plan_code||"monthly",status:"active",validUntil:row.current_period_ends_at||futureDate(31)},"resume-"+row.id)}>Reativar</button>:<button className="danger" onClick={()=>onAction({action:"set_license",workspaceId:row.id,planCode:row.plan_code||"monthly",status:"suspended",validUntil:row.current_period_ends_at},"suspend-"+row.id)}>Suspender</button>}</footer></article>)}</section></>;
}

function Settings({data,active,setActive,busy,onAction}:{data:AdminData;active:"plans"|"integrations"|"security";setActive:(value:"plans"|"integrations"|"security")=>void;busy:string;onAction:(payload:Record<string,unknown>,label:string)=>void}){
  return <><section className="settings-heading"><span>CONFIGURAÇÕES DA PLATAFORMA</span><h1>Controle comercial e segurança</h1><p>Altere uma vez aqui e a plataforma inteira utiliza a nova configuração.</p></section><nav className="settings-tabs"><button className={active==="plans"?"active":""} onClick={()=>setActive("plans")}>Planos</button><button className={active==="integrations"?"active":""} onClick={()=>setActive("integrations")}>Integrações</button><button className={active==="security"?"active":""} onClick={()=>setActive("security")}>Segurança</button></nav>{active==="plans"?<PlanSettings key={data.plans.map(plan=>plan.code+plan.updated_at).join("|")} plans={data.plans} busy={busy} onAction={onAction}/>:active==="integrations"?<IntegrationSettings integration={data.configuration.integration} configured={data.configuration.checkoutConfigured} busy={busy} onAction={onAction}/>:<SecuritySettings/>}</>;
}

function PlanSettings({plans,busy,onAction}:{plans:PlanRow[];busy:string;onAction:(payload:Record<string,unknown>,label:string)=>void}){
  const empty:PlanRow={code:"",name:"",description:"",price_cents:500,currency:"BRL",billing_interval:"month",provider_price_id:"",trial_days:7,active:1,highlighted:0,updated_at:""};
  const [drafts,setDrafts]=useState<PlanRow[]>(plans),[newPlan,setNewPlan]=useState<PlanRow|null>(null);
  const update=(index:number,partial:Partial<PlanRow>)=>setDrafts(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,...partial}:item));
  const save=(plan:PlanRow)=>onAction({action:"upsert_plan",code:plan.code,name:plan.name,description:plan.description,priceCents:plan.price_cents,interval:plan.billing_interval,trialDays:plan.trial_days,active:Boolean(plan.active),highlighted:Boolean(plan.highlighted),providerPriceId:plan.provider_price_id},"plan-"+plan.code);
  const editor=(plan:PlanRow,onChange:(partial:Partial<PlanRow>)=>void,isNew=false)=><article className="plan-editor" key={isNew?"new-plan":plan.code}><div className="plan-editor-grid"><label>Código<input disabled={!isNew} value={plan.code} placeholder="ex.: profissional" onChange={event=>onChange({code:event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/></label><label>Nome<input value={plan.name} placeholder="Nome comercial" onChange={event=>onChange({name:event.target.value})}/></label><label>Preço em reais<input type="number" min="1" step="0.01" value={(plan.price_cents/100).toFixed(2)} onChange={event=>onChange({price_cents:Math.round(Number(event.target.value)*100)})}/></label><label>Cobrança<select value={plan.billing_interval} onChange={event=>onChange({billing_interval:event.target.value as "month"|"year"})}><option value="month">Mensal</option><option value="year">Anual</option></select></label><label>Dias de teste<input type="number" min="0" max="90" value={plan.trial_days} onChange={event=>onChange({trial_days:Number(event.target.value)})}/></label></div><label className="plan-description">Descrição<textarea value={plan.description} placeholder="Explique para quem este plano é indicado" onChange={event=>onChange({description:event.target.value})}/></label><footer><label><input type="checkbox" checked={Boolean(plan.active)} onChange={event=>onChange({active:event.target.checked?1:0})}/> Disponível para venda</label><label><input type="checkbox" checked={Boolean(plan.highlighted)} onChange={event=>onChange({highlighted:event.target.checked?1:0})}/> Destacar na página</label>{isNew&&<button className="secondary" onClick={()=>setNewPlan(null)}>Cancelar</button>}<button disabled={Boolean(busy)||plan.code.length<2||!plan.name} onClick={()=>{save(plan);if(isNew)setNewPlan(null)}}>{busy==="plan-"+plan.code?"Salvando...":"Salvar plano"}</button></footer></article>;
  return <section className="plan-settings"><header><div><h2>Planos e valores</h2><p>As alterações aparecem automaticamente na página pública, na assinatura do cliente e no checkout Asaas.</p></div><button onClick={()=>setNewPlan({...empty})} disabled={Boolean(newPlan)}>＋ Novo plano</button></header>{drafts.map((plan,index)=>editor(plan,partial=>update(index,partial)))}{newPlan&&editor(newPlan,partial=>setNewPlan(current=>current?{...current,...partial}:current),true)}</section>;
}

function IntegrationSettings({integration,configured,busy,onAction}:{integration:AdminData["configuration"]["integration"];configured:boolean;busy:string;onAction:(payload:Record<string,unknown>,label:string)=>void}){
  const copy=()=>navigator.clipboard.writeText(integration.webhookUrl);
  return <section className="integration-settings"><article className="integration-card"><header><span className="asaas-mark">A$</span><div><h2>Asaas</h2><p>Checkout recorrente e liberação automática de licenças</p></div><i className={configured?"connected":"pending"}>{configured?"CONECTADO":"CONFIGURAÇÃO PENDENTE"}</i></header><div className="integration-facts"><span><small>AMBIENTE</small><b>{integration.environment==="production"?"Produção":"Sandbox"}</b></span><span><small>CHAVE DA API</small><b>{integration.apiKeyConfigured?"Configurada":"Pendente"}</b></span><span><small>TOKEN DO WEBHOOK</small><b>{integration.webhookTokenConfigured?"Configurado":"Pendente"}</b></span></div><label className="webhook-field">URL do webhook<div><input readOnly value={integration.webhookUrl}/><button onClick={copy}>Copiar</button></div></label><footer><button disabled={!integration.apiKeyConfigured||Boolean(busy)} onClick={()=>onAction({action:"test_asaas"},"test-asaas")}>{busy==="test-asaas"?"Testando...":"Testar conexão"}</button></footer></article><article className="integration-guide"><span>COMO CONECTAR</span><h3>Configuração segura em quatro passos</h3><ol><li>Crie primeiro uma conta Sandbox no Asaas e gere uma chave de API.</li><li>Nas configurações protegidas do Site, adicione <code>ASAAS_API_KEY</code>, <code>ASAAS_WEBHOOK_TOKEN</code> e <code>ASAAS_ENVIRONMENT</code>.</li><li>No Asaas, cadastre a URL acima e use o mesmo token do webhook, nunca a chave da API.</li><li>Teste a conexão aqui antes de trocar o ambiente para produção.</li></ol><p>Os valores dos planos são enviados diretamente ao checkout. Não é necessário cadastrar o mesmo preço novamente no Asaas.</p></article></section>;
}
function SecuritySettings(){return <section className="settings-card"><span className="settings-icon ok">✓</span><div><h2>Proteções administrativas</h2><p>O painel valida o Super Admin no servidor. Ocultar o menu não concede nem remove permissão.</p><ul><li>Login delegado ao ChatGPT</li><li>Workspaces isolados por proprietário e permissões</li><li>Licenças aplicadas em todas as operações de escrita</li><li>Histórico de alterações comerciais e eventos</li></ul></div></section>}
function ListHeader({eyebrow,title,text,search,setSearch}:{eyebrow:string;title:string;text:string;search:string;setSearch:(value:string)=>void}){return <section className="list-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div><label>⌕<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar por nome ou e-mail"/></label></section>}
